apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ parameters["app"] }
  namespace: ${ parameters["targetEnv"] }
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:${ parameters["version"] }
        ports:
        - containerPort: 80
